site_name: PHN Exchange Help Centre
site_url: https://www.phnexchange.com.au/
site_description: PHN Exchange Help Centre

theme:
        name: "material"
        logo: "images/icon.png"

site_dir: docs/
docs_dir: src/

nav:
        - Home: "index.md"
        - General Practices:
                  - Overview: "practices/overview.md"
                  - Practice Profile: "practices/profile.md"
                  - Data Report: "practices/data-report.md"
                  - Licensing and Agreements: "practices/licensing-agreements.md"
        - Partner PHN's:
                  - Overview: "phns/overview.md"
                  - System Specifications: "phns/system-specifications.md"
                  - Regulations: "phns/regulations.md"
                  - Reports: "phns/reports.md"
                  - Support: "phns/support.md"
                  - Security: "phns/security.md"
                  - Terms and Conditions: "phns/terms.md"
                  - Resources: "phns/resources.md"
                  - Engagement with Practices: "phns/engagement.md"
                  - PIP QI: "phns/pipqi.md"
                  - EULA: "phns/eula.md"
                  - Components:
                            - Priority Areas: "phns/components/priority-areas.md"
                            - GP Data: "phns/components/gpdata.md"
                            - ABS Atlas: "phns/components/atlas.md"
                            - Learning Management System: "phns/components/lms.md"
                            - Population Health: "phns/components/populationhealth.md"
                            - Data Extraction: "phns/components/extraction.md"
                  - PHN in a Box:
                            - Overview: "phns/phn-in-a-box/overview.md"
                            - Components: "phns/phn-in-a-box/components.md"
                            - Activity Tracking: "phns/phn-in-a-box/activity-tracking.md"
                            - Extra Features: "phns/phn-in-a-box/extra-features.md"
                            - Changelog: "phns/phn-in-a-box/changelog.md"
        - User Guide:
                  - Members: "user-guide/members.md"
                  - PHN Admins: "user-guide/phn-admins.md"
                  - Administration: "user-guide/admin.md"
        - Changelog: "changelog.md"

extra_css:
        - ../css/extra.css

markdown_extensions:
        - toc:
                  permalink: true
